// Generates the content registries in src/content/config.
// Run: bun run generate
//
// Listings hold data only, so a page that lists content never imports the content
// itself. Bodies sit behind a thunk, so a route loads the one body it renders.

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/content/config");

const HEADER = "// Generated by scripts/generate-registries.ts. Do not edit.\n";

const camel = (slug: string): string =>
  slug.replace(/-([a-z0-9])/g, (_, character: string) => character.toUpperCase());

const slugs = (tree: string): string[] =>
  readdirSync(join(ROOT, "src/content", tree))
    .filter((entry) => entry.endsWith(".tsx"))
    .map((entry) => entry.replace(/\.tsx$/, ""))
    .sort();

type Authored = {
  slug: string;
  title: string;
  description: string;
  source?: string;
  date?: string;
};

async function read(tree: string): Promise<Authored[]> {
  const entries: Authored[] = [];
  for (const slug of slugs(tree)) {
    const module = await import(`@/content/${tree}/${slug}`);
    const { body: _body, ...rest } = module[camel(slug)] as Authored & { body: unknown };
    entries.push(rest);
  }
  return entries;
}

const listing = (name: string, tree: string, type: string, entries: Authored[]): string =>
  [
    HEADER,
    `import type { ${type} } from "@/content/types/${tree.replace(/s$/, "")}";`,
    "",
    `export const ${name}: ${type}[] = ${JSON.stringify(entries, null, 2)};`,
    "",
  ].join("\n");

const bodies = (name: string, tree: string, entries: Authored[]): string =>
  [
    HEADER,
    'import type { ReactNode } from "react";',
    "",
    `export const ${name}: Record<string, () => Promise<ReactNode>> = {`,
    ...entries.map(
      (entry) =>
        `  "${entry.slug}": async () =>` +
        ` (await import("@/content/${tree}/${entry.slug}")).${camel(entry.slug)}.body,`,
    ),
    "};",
    "",
  ].join("\n");

const byNewest = (a: Authored, b: Authored): number => (b.date ?? "").localeCompare(a.date ?? "");

const docs = await read("docs");
const notes = (await read("notes")).toSorted(byNewest);
const writings = (await read("writings")).toSorted(byNewest);

writeFileSync(join(OUT, "docs.ts"), listing("docs", "docs", "DocEntry", docs));
writeFileSync(join(OUT, "doc-bodies.ts"), bodies("docBodies", "docs", docs));
writeFileSync(join(OUT, "notes.ts"), listing("notes", "notes", "NoteEntry", notes));
writeFileSync(join(OUT, "note-bodies.ts"), bodies("noteBodies", "notes", notes));
writeFileSync(join(OUT, "writings.ts"), listing("writings", "writings", "WritingEntry", writings));
writeFileSync(join(OUT, "writing-bodies.ts"), bodies("writingBodies", "writings", writings));

console.log(
  `generated listings and bodies for ${docs.length} docs, ${notes.length} notes, ${writings.length} writings`,
);
