// Generates the content registries in src/content/config.
// Run: bun scripts/generate-registries.ts && bunx oxfmt src/content/config

import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT = join(ROOT, "src/content");
const OUT = join(CONTENT, "config");

const HEADER = "// Generated by scripts/generate-registries.ts. Do not edit.\n";

const camel = (slug: string): string =>
  slug.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

const pascal = (slug: string): string => {
  const name = camel(slug);
  return `${name.charAt(0).toUpperCase()}${name.slice(1)}`;
};

const slugs = (dir: string): string[] =>
  readdirSync(join(CONTENT, dir))
    .filter((entry) => entry.endsWith(".tsx"))
    .map((entry) => entry.replace(/\.tsx$/, ""))
    .sort();

const directories = (dir: string): string[] =>
  readdirSync(join(CONTENT, dir), { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

function buildDemos(): string {
  const entries = directories("demos").flatMap((subject) =>
    slugs(`demos/${subject}`).map((variant) => ({
      key: `${subject}/${variant}`,
      local: `${pascal(subject)}${pascal(variant)}`,
      export: pascal(variant),
      path: `@/content/demos/${subject}/${variant}`,
    })),
  );

  return [
    HEADER,
    'import type { ComponentType } from "react";',
    ...entries.map((entry) => `import { ${entry.export} as ${entry.local} } from "${entry.path}";`),
    "",
    "export const demos = {",
    ...entries.map((entry) => `  "${entry.key}": ${entry.local},`),
    "} satisfies Record<string, ComponentType>;",
    "",
    "export type DemoName = keyof typeof demos;",
    "",
  ].join("\n");
}

function buildDated(dir: "notes" | "writings", type: "Note" | "Writing"): string {
  const entries = slugs(dir).map((slug) => ({
    name: camel(slug),
    path: `@/content/${dir}/${slug}`,
  }));

  return [
    HEADER,
    `import type { ${type} } from "@/content/types/${type.toLowerCase()}";`,
    ...entries.map((entry) => `import { ${entry.name} } from "${entry.path}";`),
    "",
    `export const ${dir}: ${type}[] = [${entries.map((entry) => entry.name).join(", ")}].toSorted(`,
    "  (a, b) => b.date.localeCompare(a.date),",
    ");",
    "",
  ].join("\n");
}

writeFileSync(join(OUT, "demos.ts"), buildDemos());
writeFileSync(join(OUT, "notes.ts"), buildDated("notes", "Note"));
writeFileSync(join(OUT, "writings.ts"), buildDated("writings", "Writing"));
console.log("generated demos, notes, and writings registries");
