// Generated by scripts/generate-registries.ts. Do not edit.

import type { ReactNode } from "react";

export const docBodies: Record<string, () => Promise<ReactNode>> = {
  avatar: async () => (await import("@/content/docs/avatar")).avatar.body,
  button: async () => (await import("@/content/docs/button")).button.body,
  input: async () => (await import("@/content/docs/input")).input.body,
  loaders: async () => (await import("@/content/docs/loaders")).loaders.body,
  select: async () => (await import("@/content/docs/select")).select.body,
  textarea: async () => (await import("@/content/docs/textarea")).textarea.body,
};
