// Generated by scripts/generate-registries.ts. Do not edit.

import type { ReactNode } from "react";

export const noteBodies: Record<string, () => Promise<ReactNode>> = {
  "shadows-over-borders": async () =>
    (await import("@/content/notes/shadows-over-borders")).shadowsOverBorders.body,
};
