// Generated by scripts/generate-registries.ts. Do not edit.

import type { WritingEntry } from "@/content/types/writing";

export const writings: WritingEntry[] = [
  {
    slug: "data-oriented-design-in-yukus-parser",
    title: "Data-Oriented Design in Yuku's Parser",
    description:
      "How Yuku stores a JavaScript AST as flat arrays of u32 indices instead of a pointer tree, and what follows from that in allocation, lists, backtracking, strings, and the trip into JavaScript.",
    date: "2026-06-28",
  },
];
