// Generated by scripts/generate-registries.ts. Do not edit.

import type { ComponentType } from "react";
import { Basic as AvatarBasic } from "@/content/demos/avatar/basic";
import { Fallback as AvatarFallback } from "@/content/demos/avatar/fallback";
import { Group as AvatarGroup } from "@/content/demos/avatar/group";
import { Sizes as AvatarSizes } from "@/content/demos/avatar/sizes";
import { AsLink as ButtonAsLink } from "@/content/demos/button/as-link";
import { Basic as ButtonBasic } from "@/content/demos/button/basic";
import { Colors as ButtonColors } from "@/content/demos/button/colors";
import { Elevated as ButtonElevated } from "@/content/demos/button/elevated";
import { Icons as ButtonIcons } from "@/content/demos/button/icons";
import { Loading as ButtonLoading } from "@/content/demos/button/loading";
import { Sizes as ButtonSizes } from "@/content/demos/button/sizes";
import { Basic as InputBasic } from "@/content/demos/input/basic";
import { Disabled as InputDisabled } from "@/content/demos/input/disabled";
import { Invalid as InputInvalid } from "@/content/demos/input/invalid";
import { Sizes as InputSizes } from "@/content/demos/input/sizes";
import { Basic as LoadersBasic } from "@/content/demos/loaders/basic";
import { Color as LoadersColor } from "@/content/demos/loaders/color";
import { Gallery as LoadersGallery } from "@/content/demos/loaders/gallery";
import { Sizes as LoadersSizes } from "@/content/demos/loaders/sizes";
import { Avatars as SelectAvatars } from "@/content/demos/select/avatars";
import { Basic as SelectBasic } from "@/content/demos/select/basic";
import { Descriptions as SelectDescriptions } from "@/content/demos/select/descriptions";
import { Disabled as SelectDisabled } from "@/content/demos/select/disabled";
import { Grouped as SelectGrouped } from "@/content/demos/select/grouped";
import { Icons as SelectIcons } from "@/content/demos/select/icons";
import { Invalid as SelectInvalid } from "@/content/demos/select/invalid";
import { Multiple as SelectMultiple } from "@/content/demos/select/multiple";
import { Sizes as SelectSizes } from "@/content/demos/select/sizes";
import { Basic as TextareaBasic } from "@/content/demos/textarea/basic";
import { Disabled as TextareaDisabled } from "@/content/demos/textarea/disabled";
import { Invalid as TextareaInvalid } from "@/content/demos/textarea/invalid";
import { Sizes as TextareaSizes } from "@/content/demos/textarea/sizes";

export const demos = {
  "avatar/basic": AvatarBasic,
  "avatar/fallback": AvatarFallback,
  "avatar/group": AvatarGroup,
  "avatar/sizes": AvatarSizes,
  "button/as-link": ButtonAsLink,
  "button/basic": ButtonBasic,
  "button/colors": ButtonColors,
  "button/elevated": ButtonElevated,
  "button/icons": ButtonIcons,
  "button/loading": ButtonLoading,
  "button/sizes": ButtonSizes,
  "input/basic": InputBasic,
  "input/disabled": InputDisabled,
  "input/invalid": InputInvalid,
  "input/sizes": InputSizes,
  "loaders/basic": LoadersBasic,
  "loaders/color": LoadersColor,
  "loaders/gallery": LoadersGallery,
  "loaders/sizes": LoadersSizes,
  "select/avatars": SelectAvatars,
  "select/basic": SelectBasic,
  "select/descriptions": SelectDescriptions,
  "select/disabled": SelectDisabled,
  "select/grouped": SelectGrouped,
  "select/icons": SelectIcons,
  "select/invalid": SelectInvalid,
  "select/multiple": SelectMultiple,
  "select/sizes": SelectSizes,
  "textarea/basic": TextareaBasic,
  "textarea/disabled": TextareaDisabled,
  "textarea/invalid": TextareaInvalid,
  "textarea/sizes": TextareaSizes,
} satisfies Record<string, ComponentType>;

export type DemoName = keyof typeof demos;
