// Generated by scripts/generate-registries.ts. Do not edit.

import type { NoteEntry } from "@/content/types/note";

export const notes: NoteEntry[] = [
  {
    slug: "shadows-over-borders",
    title: "Shadows over borders",
    description:
      "Why an edge drawn as a shadow stays crisp over shadows and holds on any background.",
    date: "2025-10-23",
  },
];
