// Generated by scripts/generate-registries.ts. Do not edit.

import type { Note } from "@/content/types/note";
import { shadowsOverBorders } from "@/content/notes/shadows-over-borders";

export const notes: Note[] = [shadowsOverBorders].toSorted((a, b) => b.date.localeCompare(a.date));
