// Generated by scripts/generate-registries.ts. Do not edit.

import type { ReactNode } from "react";

export const writingBodies: Record<string, () => Promise<ReactNode>> = {
  "data-oriented-design-in-yukus-parser": async () =>
    (await import("@/content/writings/data-oriented-design-in-yukus-parser"))
      .dataOrientedDesignInYukusParser.body,
};
