// Generated by scripts/generate-registries.ts. Do not edit.

import type { Writing } from "@/content/types/writing";
import { dataOrientedDesignInYukusParser } from "@/content/writings/data-oriented-design-in-yukus-parser";

export const writings: Writing[] = [dataOrientedDesignInYukusParser].toSorted((a, b) =>
  b.date.localeCompare(a.date),
);
